# Model parameters
model_name_or_path: "/home/jovyan/a100x4/DeepSeek-R1-Distill-Qwen-7B" # Base model for vLLM
adapter_path: "/home/jovyan/a100x4/KnowRL-reproduction-data/training/models/sft_output/deepseek-r1-distill-qwen-7b-sft" # LoRA adapter path
model_revision: main
torch_dtype: bfloat16
lora_r: 256
lora_alpha: 512
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: "/home/jovyan/a100x4/KnowRL-reproduction-data/training/outputs/deepseek-r1-distill-qwen-7b-rl" # Please replace with your output directory

# Dataset parameters
dataset_id_or_path: /home/jovyan/KnowRL-reproduction/data/rl/knowrl_RLdata.json 

# Swanlab parameters
report_to: swanlab
swanlab_project: "knowrl_reproduction" # Please replace with your Swanlab project name
swanlab_experiment_name: "test" # Please replace with your Swanlab experiment name

# Training parameters
max_steps: 150
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.03
seed: 42

# GRPO algorithm parameters
beta: 0.001
optim: adamw_8bit
max_prompt_length: 128
max_completion_length: 128
num_generations: 2
use_vllm: true   # enable vLLM for single GPU training
vllm_gpu_memory_utilization: 0.4
vllm_enforce_eager: false

# Logging parameters
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_steps: 50
resume_from_checkpoint: false

# Configuration file paths
grpo_config_file: "./script/grpo.yaml"


