model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
# deepspeed: ../trl/accelerate_configs/deepspeed_zero3.yaml

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj,k_proj,o_proj
lora_rank: 256
lora_alpha: 512

### dataset
dataset: knowrl_coldstart # e.g., knowrl_coldstart
dataset_dir: home/zhangjunwei/KnowRL-reproduction/data/coldstart
template: qwen
cutoff_len: 3072
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data22/zhangjunwei/knowrl_training/models/sft_output/test-deepseek-r1-distilled-qwen-7b-sft # e.g., /adapter-saves/MyModel-SFT
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_strategy: 'steps'

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
