name: knowrl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - nvidia::cuda-toolkit=12.1
  - pytorch::pytorch=2.5.1
  - pytorch::torchvision=0.20.1
  - pytorch::torchaudio=2.5.1
  - pytorch::pytorch-cuda=12.1
  - numpy=1.26.4
  - pandas=2.2.3
  - pillow=10.4.0
  - requests=2.32.3
  - pyyaml=6.0.2
  - tqdm=4.67.1
  - pip:
    - unsloth==2025.3.18
    - accelerate==1.3.0
    - bitsandbytes==0.45.1
    - datasets==3.1.0
    - deepspeed==0.15.4
    - flash_attn==2.7.4.post1
    - huggingface-hub==0.26.0
    - transformers==4.50.0
    - tokenizers==0.21.0
    - safetensors==0.5.2
    - peft==0.14.0
    - trl==0.14.0
    - sentence-transformers==2.3.0
    - sentencepiece==0.2.0
    - openai==1.61.0
    - swanlab==0.4.6
    - swanboard==0.1.7b1
    - swankit==0.1.2b6
    - vllm==0.7.0
    - outlines==0.1.11
    - outlines_core==0.1.26
    - xformers==0.0.28.post3
    - einops==0.8.0
    - fastapi==0.115.8
    - uvicorn==0.34.0
    - wandb==0.19.5
    - tensorboard==2.18.0
    - ray==2.41.0
    - ninja==1.11.1.3
    - packaging==24.2
    - psutil==6.1.1
    - pynvml==12.0.0
    - py-cpuinfo==9.0.0
    - nvidia-ml-py==12.570.86
    - protobuf==5.29.3
    - grpcio==1.70.0
    - google-api-core==2.24.1
    - google-auth==2.38.0
    - compressed-tensors==0.9.0
    - lm-format-enforcer==0.10.9
    - mistral_common==1.5.2
    - modelscope==1.22.3
    - opencv-python-headless==4.11.0.86
    - cos-python-sdk-v5==1.9.33
    - beautifulsoup4==4.13.3
    - jupyter==1.1.1
    - jupyterlab==4.3.5
    - notebook==7.3.2
    - matplotlib-inline==0.1.7
    - ipython==8.12.3
    - ipykernel==6.29.5
    - ipywidgets==8.1.5